Update autorebase.yaml

diff --git a/.github/workflows/autorebase.yaml b/.github/workflows/autorebase.yaml
--- a/.github/workflows/autorebase.yaml
+++ b/.github/workflows/autorebase.yaml
@@ -40,11 +40,7 @@ jobs:
 
                       git fetch origin $HEAD_REF
                       git checkout $HEAD_REF
-                      git rebase origin/dev
-                      if [ $? -ne 0 ]; then
-                        echo "Conflit détecté : abandon du rebase."
-                        git rebase --abort
-                      fi
+                      git rebase origin/dev || (echo "Conflit détecté : abandon du rebase." && git rebase --abort)
 
                       git push origin $HEAD_REF --force-with-lease
                       echo "✅ PR #$NUMBER rebasée avec succès"
